package com.mrxu.cloud.file.mapper;

import com.mrxu.cloud.file.domain.Files;
import com.mrxu.cloud.file.domain.FilesExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface FilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    long countByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    int deleteByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    int insertSelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    List<Files> selectByExampleWithRowbounds(FilesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    List<Files> selectByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    Files selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") Files record, @Param("example") FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    int updateByExample(@Param("record") Files record, @Param("example") FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    int updateByPrimaryKeySelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Wed Jun 20 16:22:05 CST 2018
     */
    int updateByPrimaryKey(Files record);
}