package com.mrxu.cloud.file.mapper;

import com.mrxu.cloud.file.domain.FileType;
import com.mrxu.cloud.file.domain.FileTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FileTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int countByExample(FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int deleteByExample(FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int insert(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int insertSelective(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    List<FileType> selectByExampleWithRowbounds(FileTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    List<FileType> selectByExample(FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    FileType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") FileType record, @Param("example") FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int updateByExample(@Param("record") FileType record, @Param("example") FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int updateByPrimaryKeySelective(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int updateByPrimaryKey(FileType record);
}