package com.mrxu.cloud.file.mapper;

import com.mrxu.cloud.file.domain.FileTransSchedule;
import com.mrxu.cloud.file.domain.FileTransScheduleExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface FileTransScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    long countByExample(FileTransScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int deleteByExample(FileTransScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int insert(FileTransSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int insertSelective(FileTransSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    List<FileTransSchedule> selectByExampleWithRowbounds(FileTransScheduleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    List<FileTransSchedule> selectByExample(FileTransScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    FileTransSchedule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") FileTransSchedule record, @Param("example") FileTransScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int updateByExample(@Param("record") FileTransSchedule record, @Param("example") FileTransScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int updateByPrimaryKeySelective(FileTransSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int updateByPrimaryKey(FileTransSchedule record);
}