package com.mrxu.cloud.file.mapper;

import com.mrxu.cloud.file.domain.FileTypeExtension;
import com.mrxu.cloud.file.domain.FileTypeExtensionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FileTypeExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int countByExample(FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int deleteByExample(FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int insert(FileTypeExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int insertSelective(FileTypeExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    List<FileTypeExtension> selectByExampleWithRowbounds(FileTypeExtensionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    List<FileTypeExtension> selectByExample(FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    FileTypeExtension selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") FileTypeExtension record, @Param("example") FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int updateByExample(@Param("record") FileTypeExtension record, @Param("example") FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int updateByPrimaryKeySelective(FileTypeExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    int updateByPrimaryKey(FileTypeExtension record);
}