package com.mrxu.cloud.file.mapper;

import com.mrxu.cloud.file.domain.FileTypeExtension;
import com.mrxu.cloud.file.domain.FileTypeExtensionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface FileTypeExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    long countByExample(FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int deleteByExample(FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int insert(FileTypeExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int insertSelective(FileTypeExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    List<FileTypeExtension> selectByExampleWithRowbounds(FileTypeExtensionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    List<FileTypeExtension> selectByExample(FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    FileTypeExtension selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") FileTypeExtension record, @Param("example") FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int updateByExample(@Param("record") FileTypeExtension record, @Param("example") FileTypeExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int updateByPrimaryKeySelective(FileTypeExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    int updateByPrimaryKey(FileTypeExtension record);
}