package com.mrxu.cloud.file.mybatis.mapper;

import com.mrxu.cloud.file.mybatis.entity.FileInfo;
import com.mrxu.cloud.file.mybatis.entity.FileInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    int countByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    int deleteByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    int insert(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    int insertSelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    List<FileInfo> selectByExampleWithRowbounds(FileInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    List<FileInfo> selectByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    FileInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") FileInfo record, @Param("example") FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    int updateByExample(@Param("record") FileInfo record, @Param("example") FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    int updateByPrimaryKeySelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated Tue May 15 16:44:04 CST 2018
     */
    int updateByPrimaryKey(FileInfo record);
}