package com.mrxu.cloud.file.domain;


import com.mrxu.cloud.common.entity.BaseEntity;

public class FileTypeExtension extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type_extension.id
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type_extension.type
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type_extension.extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type_extension.description
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type_extension.id
     *
     * @return the value of file_type_extension.id
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type_extension.id
     *
     * @param id the value for file_type_extension.id
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type_extension.type
     *
     * @return the value of file_type_extension.type
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type_extension.type
     *
     * @param type the value for file_type_extension.type
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type_extension.extension
     *
     * @return the value of file_type_extension.extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type_extension.extension
     *
     * @param extension the value for file_type_extension.extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type_extension.description
     *
     * @return the value of file_type_extension.description
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type_extension.description
     *
     * @param description the value for file_type_extension.description
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FileTypeExtension other = (FileTypeExtension) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getExtension() == null ? other.getExtension() == null : this.getExtension().equals(other.getExtension()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type_extension
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getExtension() == null) ? 0 : getExtension().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}