package com.mrxu.cloud.file.domain;


import com.mrxu.cloud.common.entity.BaseEntity;

public class FileTransSchedule extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.id
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.file_id
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.file_name
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.file_path
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.origin_url
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String originUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.target_type
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.process_instance
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private String processInstance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.gmt_modified
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.gmt_create
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_trans_schedule.schedule_num
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    private Integer scheduleNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.id
     *
     * @return the value of file_trans_schedule.id
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.id
     *
     * @param id the value for file_trans_schedule.id
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.file_id
     *
     * @return the value of file_trans_schedule.file_id
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.file_id
     *
     * @param fileId the value for file_trans_schedule.file_id
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.file_name
     *
     * @return the value of file_trans_schedule.file_name
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.file_name
     *
     * @param fileName the value for file_trans_schedule.file_name
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.file_path
     *
     * @return the value of file_trans_schedule.file_path
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.file_path
     *
     * @param filePath the value for file_trans_schedule.file_path
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.origin_url
     *
     * @return the value of file_trans_schedule.origin_url
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getOriginUrl() {
        return originUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.origin_url
     *
     * @param originUrl the value for file_trans_schedule.origin_url
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setOriginUrl(String originUrl) {
        this.originUrl = originUrl == null ? null : originUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.target_type
     *
     * @return the value of file_trans_schedule.target_type
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.target_type
     *
     * @param targetType the value for file_trans_schedule.target_type
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.process_instance
     *
     * @return the value of file_trans_schedule.process_instance
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public String getProcessInstance() {
        return processInstance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.process_instance
     *
     * @param processInstance the value for file_trans_schedule.process_instance
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setProcessInstance(String processInstance) {
        this.processInstance = processInstance == null ? null : processInstance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.gmt_modified
     *
     * @return the value of file_trans_schedule.gmt_modified
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.gmt_modified
     *
     * @param gmtModified the value for file_trans_schedule.gmt_modified
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.gmt_create
     *
     * @return the value of file_trans_schedule.gmt_create
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.gmt_create
     *
     * @param gmtCreate the value for file_trans_schedule.gmt_create
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_trans_schedule.schedule_num
     *
     * @return the value of file_trans_schedule.schedule_num
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public Integer getScheduleNum() {
        return scheduleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_trans_schedule.schedule_num
     *
     * @param scheduleNum the value for file_trans_schedule.schedule_num
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    public void setScheduleNum(Integer scheduleNum) {
        this.scheduleNum = scheduleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FileTransSchedule other = (FileTransSchedule) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()))
            && (this.getOriginUrl() == null ? other.getOriginUrl() == null : this.getOriginUrl().equals(other.getOriginUrl()))
            && (this.getTargetType() == null ? other.getTargetType() == null : this.getTargetType().equals(other.getTargetType()))
            && (this.getProcessInstance() == null ? other.getProcessInstance() == null : this.getProcessInstance().equals(other.getProcessInstance()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getScheduleNum() == null ? other.getScheduleNum() == null : this.getScheduleNum().equals(other.getScheduleNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_trans_schedule
     *
     * @mbg.generated Mon Jun 18 22:29:30 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        result = prime * result + ((getOriginUrl() == null) ? 0 : getOriginUrl().hashCode());
        result = prime * result + ((getTargetType() == null) ? 0 : getTargetType().hashCode());
        result = prime * result + ((getProcessInstance() == null) ? 0 : getProcessInstance().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getScheduleNum() == null) ? 0 : getScheduleNum().hashCode());
        return result;
    }
}