package com.mrxu.cloud.file.domain;

import java.util.ArrayList;
import java.util.List;

public class FileTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public FileTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTargetTypeIsNull() {
            addCriterion("target_type is null");
            return (Criteria) this;
        }

        public Criteria andTargetTypeIsNotNull() {
            addCriterion("target_type is not null");
            return (Criteria) this;
        }

        public Criteria andTargetTypeEqualTo(String value) {
            addCriterion("target_type =", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeNotEqualTo(String value) {
            addCriterion("target_type <>", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeGreaterThan(String value) {
            addCriterion("target_type >", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("target_type >=", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeLessThan(String value) {
            addCriterion("target_type <", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeLessThanOrEqualTo(String value) {
            addCriterion("target_type <=", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeLike(String value) {
            addCriterion("target_type like", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeNotLike(String value) {
            addCriterion("target_type not like", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeIn(List<String> values) {
            addCriterion("target_type in", values, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeNotIn(List<String> values) {
            addCriterion("target_type not in", values, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeBetween(String value1, String value2) {
            addCriterion("target_type between", value1, value2, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeNotBetween(String value1, String value2) {
            addCriterion("target_type not between", value1, value2, "targetType");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIsNull() {
            addCriterion("process_instance is null");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIsNotNull() {
            addCriterion("process_instance is not null");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceEqualTo(String value) {
            addCriterion("process_instance =", value, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceNotEqualTo(String value) {
            addCriterion("process_instance <>", value, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceGreaterThan(String value) {
            addCriterion("process_instance >", value, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceGreaterThanOrEqualTo(String value) {
            addCriterion("process_instance >=", value, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceLessThan(String value) {
            addCriterion("process_instance <", value, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceLessThanOrEqualTo(String value) {
            addCriterion("process_instance <=", value, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceLike(String value) {
            addCriterion("process_instance like", value, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceNotLike(String value) {
            addCriterion("process_instance not like", value, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceIn(List<String> values) {
            addCriterion("process_instance in", values, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceNotIn(List<String> values) {
            addCriterion("process_instance not in", values, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceBetween(String value1, String value2) {
            addCriterion("process_instance between", value1, value2, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessInstanceNotBetween(String value1, String value2) {
            addCriterion("process_instance not between", value1, value2, "processInstance");
            return (Criteria) this;
        }

        public Criteria andProcessModeIsNull() {
            addCriterion("process_mode is null");
            return (Criteria) this;
        }

        public Criteria andProcessModeIsNotNull() {
            addCriterion("process_mode is not null");
            return (Criteria) this;
        }

        public Criteria andProcessModeEqualTo(String value) {
            addCriterion("process_mode =", value, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeNotEqualTo(String value) {
            addCriterion("process_mode <>", value, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeGreaterThan(String value) {
            addCriterion("process_mode >", value, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeGreaterThanOrEqualTo(String value) {
            addCriterion("process_mode >=", value, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeLessThan(String value) {
            addCriterion("process_mode <", value, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeLessThanOrEqualTo(String value) {
            addCriterion("process_mode <=", value, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeLike(String value) {
            addCriterion("process_mode like", value, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeNotLike(String value) {
            addCriterion("process_mode not like", value, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeIn(List<String> values) {
            addCriterion("process_mode in", values, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeNotIn(List<String> values) {
            addCriterion("process_mode not in", values, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeBetween(String value1, String value2) {
            addCriterion("process_mode between", value1, value2, "processMode");
            return (Criteria) this;
        }

        public Criteria andProcessModeNotBetween(String value1, String value2) {
            addCriterion("process_mode not between", value1, value2, "processMode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_type
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 28 17:32:02 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_type
     *
     * @mbggenerated Thu Jun 28 17:32:02 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}